# Generated by Django 5.1.6 on 2025-03-06 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.IntegerField(help_text='Укажите номер стола', verbose_name='Номер стола')),
                ('items', models.JSONField(help_text='Укажите блюдо', verbose_name='список заказанных блюд с ценами')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('WT', 'В ожидании'), ('RD', 'Готово'), ('PD', 'Оплачено')], default='WT', max_length=2, verbose_name='Статус заказа')),
            ],
        ),
    ]
